name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build apps image
    if: startswith(github.event.comment.body, '/imagebuild_apps')
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto build image
        id: autobuild
        env:
          domain: ghcr.io
          repo: ${{ github.repository_owner }}
          username: cuisongliu
          password: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          commentbody="${{github.event.comment.body}}"
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          echo "deb [trusted=yes] https://apt.fury.io/labring/ /" | sudo tee /etc/apt/sources.list.d/labring.list
          sudo apt update
          sudo apt install sealos
          echo "app: $app"
          echo "version: $version"
          echo "start to build $app:$version"
          export PATH=${PATH}:$(pwd)
          #wget https://github.com/labring/sealos/releases/download/v$sealos/sealos_${sealos}_linux_amd64.tar.gz
          #tar -zxvf sealos_${sealos}_linux_amd64.tar.gz
          #chmod a+x sealos
          #sudo mv sealos /usr/bin/
          #wget https://sealyun-home.oss-accelerate.aliyuncs.com/images/buildah.linux.amd64 --no-check-certificate -O buildah && chmod a+x buildah
          #sudo mv buildah /usr/bin/
          cd $app/$version
          filename=Kubefile
          if  [ -f Dockerfile ]; then
            filename=Dockerfile
          fi
           if  [ -f Sealfile ]; then
            filename=Sealfile
          fi
          if  [ -f init.sh ]; then
            bash init.sh
          fi
          sudo sealos login  -u $username -p $password $domain
          sudo sealos build -t $domain/$repo/$app:$version -f $filename .  > output.log
          sudo sealos push $domain/$repo/$app:$version >> output.log
          echo "sealos push $domain/$repo/$app:$version success"
          body="$(cat output.log)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::$body"
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            ${{ steps.autobuild.outputs.body }}
            ```
            detail log please view [autobuild](https://github.com/${{ github.repository_owner }}/infra/actions/workflows/autobuild.yml)
